services:
  macuin-app:
    build: .
    container_name: macuin_flask_container
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      INIT_MOCK_DATA: "true"
      DATABASE_URL: "sqlite:///:memory:"
    volumes:
      - .:/app
